export const container: string;
export const mapContainer: string;
export const title: string;
export const infoTitle: string;
export const button: string;
export const input: string;
export const formContainer: string;
export const formHeading: string;
export const form: string;
